export const AUDIO_SEEKING = 'AUDIO_SEEKING'
export const AUDIO_TOGGLE = 'AUDIO_TOGGLE'

export const AUTH_DISCONNECT = 'AUTH_DISCONNECT'
export const AUTH_FAILURE = 'AUTH_FAILURE'
export const AUTH_REQUEST = 'AUTH_REQUEST'
export const AUTH_SUCCESS = 'AUTH_SUCCESS'

export const FAVORITE_FAILURE = 'FAVORITES_FAILURE'
export const FAVORITE_REQUEST = 'FAVORITES_REQUEST'
export const FAVORITE_SUCCESS = 'FAVORITES_SUCCESS'

export const FOLLOWERS_FAILURE = 'FOLLOWERS_FAILURE'
export const FOLLOWERS_REQUEST = 'FOLLOWERS_REQUEST'
export const FOLLOWERS_SUCCESS = 'FOLLOWERS_SUCCESS'

export const FOLLOWINGS_FAILURE = 'FOLLOWINGS_FAILURE'
export const FOLLOWINGS_REQUEST = 'FOLLOWINGS_REQUEST'
export const FOLLOWINGS_SUCCESS = 'FOLLOWINGS_SUCCESS'

export const GENRE_FAILURE = 'GENRE_FAILURE'
export const GENRE_REQUEST = 'GENRE_REQUEST'
export const GENRE_SUCCESS = 'GENRE_SUCCESS'

export const NOTIF_PUBLISH = 'NOTIF_PUBLISH'
export const NOTIF_DESTROY = 'NOTIF_DESTROY'
export const NOTIF_CLEAR = 'NOTIF_CLEAR'

export const PAGINATION_SET = 'PAGINATION_SET'

export const PLAYLIST_FAILURE = 'PLAYLIST_FAILURE'
export const PLAYLIST_REQUEST = 'PLAYLIST_REQUEST'
export const PLAYLIST_SUCCESS = 'PLAYLIST_SUCCESS'

export const SEARCH_FAILURE = 'SEARCH_FAILURE'
export const SEARCH_REQUEST = 'SEARCH_REQUEST'
export const SEARCH_SUCCESS = 'SEARCH_SUCCESS'

export const SET_AUDIO_DURATION = 'SET_AUDIO_DURATION'
export const SET_AUDIO_POSITION = 'SET_AUDIO_POSITION'

export const STREAM_ENDED = 'STREAM_ENDED'
export const STREAM_FAILURE = 'STREAM_FAILURE'
export const STREAM_REQUEST = 'STREAM_REQUEST'
export const STREAM_SUCCESS = 'STREAM_SUCCESS'

export const TAG_FAILURE = 'TAG_FAILURE'
export const TAG_REQUEST = 'TAG_REQUEST'
export const TAG_SUCCESS = 'TAG_SUCCESS'

export const TEST_BROWSER = 'TEST_BROWSER'

export const TOGGLE_CLOSE_ALL = 'TOGGLE_CLOSE_ALL'
export const TOGGLE_DROPDOWN = 'TOGGLE_DROPDOWN'
export const TOGGLE_MENU = 'TOGGLE_MENU'
export const TOGGLE_MODAL = 'TOGGLE_MODAL'
export const TOGGLE_NAVBAR = 'TOGGLE_NAVBAR'
export const TOGGLE_PROFILE_MENU = 'TOGGLE_PROFILE_MENU'
export const TOGGLE_TRACKLIST = 'TOGGLE_TRACKLIST'

export const TRACK_COMMENTS_FAILURE = 'TRACK_COMMENTS_FAILURE'
export const TRACK_COMMENTS_REQUEST = 'TRACK_COMMENTS_REQUEST'
export const TRACK_COMMENTS_SUCCESS = 'TRACK_COMMENTS_SUCCESS'

export const TRACK_FAILURE = 'TRACK_FAILURE'
export const TRACK_ADD = 'TRACK_ADD'
export const TRACK_REQUEST = 'TRACK_REQUEST'
export const TRACK_SUCCESS = 'TRACK_SUCCESS'

export const USER_FAILURE = 'USER_FAILURE'
export const USER_REQUEST = 'USER_REQUEST'
export const USER_SUCCESS = 'USER_SUCCESS'

export const USER_TRACKS_FAILURE = 'USER_TRACKS_FAILURE'
export const USER_TRACKS_REQUEST = 'USER_TRACKS_REQUEST'
export const USER_TRACKS_SUCCESS = 'USER_TRACKS_SUCCESS'

export const VOLUME_CHANGE = 'VOLUME_CHANGE'
export const VOLUME_DRAGGING = 'VOLUME_DRAGGING'
export const VOLUME_EXPAND = 'VOLUME_EXPAND'
export const VOLUME_MUTE = 'VOLUME_MUTE'

export const MY_PROFILE_REQUEST = 'MY_PROFILE_REQUEST'
export const MY_PROFILE_SUCCESS = 'MY_PROFILE_SUCCESS'
export const MY_PROFILE_FAILURE = 'MY_PROFILE_FAILURE'

export const MY_TRACK_ACTIVITIES_REQUEST = 'MY_TRACK_ACTIVITIES_REQUEST'
export const MY_TRACK_ACTIVITIES_SUCCESS = 'MY_TRACK_ACTIVITIES_SUCCESS'
export const MY_TRACK_ACTIVITIES_FAILURE = 'MY_TRACK_ACTIVITIES_FAILURE'

export const MY_TRACKS_REQUEST = 'MY_TRACKS_REQUEST'
export const MY_TRACKS_SUCCESS = 'MY_TRACKS_SUCCESS'
export const MY_TRACKS_FAILURE = 'MY_TRACKS_FAILURE'
export const MY_TRACKS_DELETE = 'MY_TRACKS_DELETE'
export const MY_TRACKS_PUT = 'MY_TRACKS_PUT'

export const MY_PLAYLISTS_REQUEST = 'MY_PLAYLISTS_REQUEST'
export const MY_PLAYLISTS_SUCCESS = 'MY_PLAYLISTS_SUCCESS'
export const MY_PLAYLISTS_FAILURE = 'MY_PLAYLISTS_FAILURE'
export const MY_PLAYLISTS_DELETE = 'MY_PLAYLISTS_DELETE'
export const MY_PLAYLISTS_PUT = 'MY_PLAYLISTS_PUT'

// export const MY_COMMENTS_REQUEST = 'MY_COMMENTS_REQUEST'
// export const MY_COMMENTS_SUCCESS = 'MY_COMMENTS_SUCCESS'
// export const MY_COMMENTS_FAILURE = 'MY_COMMENTS_FAILURE'
// export const MY_COMMENTS_DELETE = 'MY_COMMENTS_DELETE'
// export const MY_COMMENTS_PUT = 'MY_COMMENTS_PUT'

export const MY_FOLLOWINGS_REQUEST = 'MY_FOLLOWINGS_REQUEST'
export const MY_FOLLOWINGS_SUCCESS = 'MY_FOLLOWINGS_SUCCESS'
export const MY_FOLLOWINGS_FAILURE = 'MY_FOLLOWINGS_FAILURE'
export const MY_FOLLOWINGS_DELETE = 'MY_FOLLOWINGS_DELETE'
export const MY_FOLLOWINGS_PUT = 'MY_FOLLOWINGS_PUT'

// export const MY_FOLLOWERS_REQUEST = 'MY_FOLLOWERS_REQUEST'
// export const MY_FOLLOWERS_SUCCESS = 'MY_FOLLOWERS_SUCCESS'
// export const MY_FOLLOWERS_FAILURE = 'MY_FOLLOWERS_FAILURE'

export const SYNC_TRACKS = 'SYNC_TRACKS'
export const SYNC_PLAYLISTS = 'SYNC_PLAYLISTS'
export const SYNC_COMMENTS = 'SYNC_COMMENTS'
export const SYNC_FOLLOWINGS = 'SYNC_FOLLOWINGS'
