export const AUDIO_SEEKING = 'AUDIO_SEEKING'
export const AUDIO_TOGGLE = 'AUDIO_TOGGLE'

export const AUTH_DISCONNECT = 'AUTH_DISCONNECT'
export const AUTH_FAILURE = 'AUTH_FAILURE'
export const AUTH_REQUEST = 'AUTH_REQUEST'
export const AUTH_SUCCESS = 'AUTH_SUCCESS'

export const FAVORITE_FAILURE = 'FAVORITES_FAILURE'
export const FAVORITE_REQUEST = 'FAVORITES_REQUEST'
export const FAVORITE_SUCCESS = 'FAVORITES_SUCCESS'

export const GENRE_FAILURE = 'GENRE_FAILURE'
export const GENRE_REQUEST = 'GENRE_REQUEST'
export const GENRE_SUCCESS = 'GENRE_SUCCESS'

export const NOTIF_PUBLISH = 'NOTIF_PUBLISH'
export const NOTIF_DESTROY = 'NOTIF_DESTROY'
export const NOTIF_CLEAR = 'NOTIF_CLEAR'

export const PAGINATION_LOAD = 'PAGINATION_LOAD'
export const PAGINATION_SET = 'PAGINATION_SET'

export const PLAYLIST_FAILURE = 'PLAYLIST_FAILURE'
export const PLAYLIST_REQUEST = 'PLAYLIST_REQUEST'
export const PLAYLIST_SUCCESS = 'PLAYLIST_SUCCESS'

export const RESET_ERROR_MESSAGE = 'RESET_ERROR_MESSAGE'

export const SEARCH_FAILURE = 'SEARCH_FAILURE'
export const SEARCH_REQUEST = 'SEARCH_REQUEST'
export const SEARCH_SUCCESS = 'SEARCH_SUCCESS'

export const SET_AUDIO_DURATION = 'SET_AUDIO_DURATION'
export const SET_AUDIO_POSITION = 'SET_AUDIO_POSITION'

export const STREAM_ENDED = 'STREAM_ENDED'
export const STREAM_FAILURE = 'STREAM_FAILURE'
export const STREAM_REQUEST = 'STREAM_REQUEST'
export const STREAM_SUCCESS = 'STREAM_SUCCESS'

export const TAG_FAILURE = 'TAG_FAILURE'
export const TAG_REQUEST = 'TAG_REQUEST'
export const TAG_SUCCESS = 'TAG_SUCCESS'

export const TOGGLE_MENU = 'TOGGLE_MENU'
export const TOGGLE_MODAL = 'TOGGLE_MODAL'
export const TOGGLE_TRACKLIST = 'TOGGLE_TRACKLIST'
export const TOGGLE_NAVBAR = 'TOGGLE_NAVBAR'
export const TOGGLE_PROFILE_MENU = 'TOGGLE_PROFILE_MENU'

export const TRACK_COMMENTS_FAILURE = 'TRACK_COMMENTS_FAILURE'
export const TRACK_COMMENTS_REQUEST = 'TRACK_COMMENTS_REQUEST'
export const TRACK_COMMENTS_SUCCESS = 'TRACK_COMMENTS_SUCCESS'

export const TRACK_FAILURE = 'TRACK_FAILURE'
export const TRACK_PUSH = 'TRACK_PUSH'
export const TRACK_REQUEST = 'TRACK_REQUEST'
export const TRACK_SUCCESS = 'TRACK_SUCCESS'

export const USER_FAILURE = 'USER_FAILURE'
export const USER_REQUEST = 'USER_REQUEST'
export const USER_SUCCESS = 'USER_SUCCESS'

export const VOLUME_CHANGE = 'VOLUME_CHANGE'
export const VOLUME_DRAGGING = 'VOLUME_DRAGGING'
export const VOLUME_EXPAND = 'VOLUME_EXPAND'
export const VOLUME_MUTE = 'VOLUME_MUTE'
